---
apiVersion: v1
kind: Namespace
metadata:
  name: vilniusphp
  labels:
    name: vilniusphp
---
kind: Service
apiVersion: v1
metadata:
  name: vilniusphp
  namespace: vilniusphp
spec:
  type: ClusterIP
  externalIPs:
  - 192.168.57.21
  - 192.168.57.22
  selector:
    app: nginx
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: vilniusphp
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: sergejkurakin/vilniusphp-demo:3
        ports:
        - containerPort: 80
---

